apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - virtualservice.yaml
  - secret.yaml
  - gateway.yaml
images:
  - name: bearlu/httpserver
    newTag: 1.0
